name: Continuous Integration

on:
  workflow_call:

jobs:
  format-lint-test-validate:
    name: Format, Lint, Test, and Validate
    uses: ./.github/workflows/shared.yml
    secrets:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
