name: Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment to remove AWS resources for?
        options:
          - release
          - staging # remove this line in a real-world scenario
          - prod # remove this line in a real-world scenario

env:
  AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform init
        run: docker compose -f ./infra/docker-compose.yml run --rm terraform -chdir=deploy/ init
      - name: Terraform destroy
        run: |
          workspace=${{ github.event.inputs.environment }}
          docker compose -f ./infra/docker-compose.yml run --rm terraform -chdir=deploy/ workspace select -or-create ${workspace}
          docker compose -f ./infra/docker-compose.yml run --rm terraform -chdir=deploy/ destroy -auto-approve
