name: Format, Lint, Test, and Validate

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
        description: "Username for DockerHub auth"
      DOCKERHUB_TOKEN:
        required: true
        description: "Token for DockerHub auth"

jobs:
  format-lint-test-validate:
    name: Format, Lint, Test, and Validate
    runs-on: ubuntu-22.04
    steps:
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ vars.DOCKERHUB_USER }}
      #     password: ${{ vars.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check linting
        run: docker-compose run --rm app sh -c "flake8"
      - name: Check formatting
        run: docker-compose run --rm app sh -c "black ."
      # - name: Check typing
      #   run: docker-compose run --rm app sh -c "mypy ."
      - name: Execute tests
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Init terraform in setup
        run: cd infra && docker compose run --rm terraform -chdir=deploy/ init -backend=false
      - name: Init terraform in deploy
        run: cd infra && docker compose run --rm terraform -chdir=setup/ init -backend=false
      - name: Validate terraform in setup
        run: cd infra && docker compose run --rm terraform -chdir=setup/ validate
      - name: Check terraform formatting in setup
        run: cd infra && docker compose run --rm terraform -chdir=setup/ fmt -check
      - name: Validate terraform in deploy
        run: cd infra && docker compose run --rm terraform -chdir=deploy/ validate
      - name: Check terraform formatting in deploy
        run: cd infra && docker compose run --rm terraform -chdir=deploy/ fmt -check
